### ISSUE TITLE
Transaction id is not included in GetBlock request

### ISSUE THREAD

**Issue by mnebliienko-sixclovers** [algorand/java-algorand-sdk#234]
GetBlock request returns information about transactions, confirmed in the specified round. But transaction id is not there and we require it. We request adding transaction id to response for that request.

**Comment by mnebliienko-sixclovers** [comment]
See the screenshot for example

https://i.imgur.com/zkLuQ3Y.png

**Comment by winder** [comment]
@mnebliienko-sixclovers to get the transaction ID you have two options:
1) serialize these objects into a `SignedTransaction` object and call the `txID()` function
2) use Indexer.

**Comment by mnebliienko-sixclovers** [comment]
@winder transaction returned is not compete so txID that is returned is wrong

**Comment by nkavian** [comment]
@winder another way to look at this reported issue is to ask if the SDK could include a v2 model for `BlockResponse` that actually implements the full model instead of just a hash map of objects. And by doing so, give us access to the txID.

**Comment by winder** [comment]
It's possible to serialize the transaction/signed transaction object from the block response into a SignedTransaction object. I haven't gone through the exercise, but this is the same endpoint Indexer uses so I know it's possible in theory. The problem is that going from the initial msgpack response -> Map<String,Object> ->SignedTransaction leaves soom room for serialization to be slightly wrong. Having a proper Block type is really what you need, unfortunately, we don't have that in the Java SDK.

**Comment by winder** [comment]
> @winder transaction returned is not compete so txID that is returned is wrong

I was mistaken here. This transaction object doesn't include the Genesis Hash and Genesis ID field. Those need to be fetched from algod and put back in the transaction before computing the TXID.

**Comment by Kseng** [comment]
any solution for this issue?  please provide some sample code also.
I'm encounter for this, need to get transaction id.
