### ISSUE TITLE
MethodCallParams.Builder pulling v1 TransactionParams

### ISSUE THREAD

**Issue by deanstef** [algorand/java-algorand-sdk#323]
### Subject of the issue

The method `setSuggestedParams()` of the Java object `MethodCallParams.Builder` used for ABI calls with ATC is pulling `TransactionParams` from v1 API instead of v2's `TransactionParametersResponse`. These objects are serialized differently, as a consequence it is not possible to call ABI methods with the Java SDK.

### Your environment

* Software version: `sandbox: 3.5.139117.dev`

### Steps to reproduce

    TransactionParametersResponse sp = algod.TransactionParams().execute().body();

    // create methodCallParams by builder (or create by constructor) for txntest method
    MethodCallParams.Builder methodCallParamsBuilderTxn = new MethodCallParams.Builder();
    // methodCallParams txn: commons params
    ...
    methodCallParamsBuilderTxn.setSuggestedParams(sp);

### Expected behaviour
Set suggested params pulled from algod v2 API as `TransactionParametersResponse` object

### Actual behaviour
Getting error:
`The method setSuggestedParams(TransactionParams) in the type MethodCallParams.Builder is not applicable for the arguments (TransactionParametersResponse)`

**Comment by deanstef** [comment]
@winder do you mind to have a look at it?

**Comment by winder** [comment]
@algoanne @michaeldiamant looks like this code would benefit from a similar approach to the transaction builder, which has helpers for the v1 and v2 API. [See the two "suggestedParams" and "lookupParams" methods here](https://algorand.github.io/java-algorand-sdk/com/algorand/algosdk/builder/transaction/TransactionBuilder.html#suggestedParams(com.algorand.algosdk.algod.client.model.TransactionParams)
).

[Here is the method in question, which only supports the v1 API](https://algorand.github.io/java-algorand-sdk/com/algorand/algosdk/transaction/MethodCallParams.html#%3Cinit%3E(java.lang.Long,com.algorand.algosdk.abi.Method,java.util.List,java.lang.String,com.algorand.algosdk.algod.client.model.TransactionParams,com.algorand.algosdk.transaction.Transaction.OnCompletion,byte[],byte[],java.math.BigInteger,java.math.BigInteger,java.math.BigInteger,java.math.BigInteger,java.lang.String,com.algorand.algosdk.transaction.TxnSigner,java.util.List,java.util.List,java.util.List,com.algorand.algosdk.crypto.TEALProgram,com.algorand.algosdk.crypto.TEALProgram,java.lang.Long,java.lang.Long,java.lang.Long,java.lang.Long,java.lang.Long))

I'm not familiar with the AtomicTransactionComposer, but my first impression is that the design for this feature overlaps with the preexisting transaction builders. Instead of using the "params" pattern, and a new builder convention why not add a new "MethodCallTransactionBuilder" class to the other builders?

**Comment by jasonpaulos** [comment]
I've created PR #324 to fix this issue, mostly following @winder's suggestion.
